from sqlalchemy import Column, Integer, String, DateTime, JSON, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.core.postgres import Base


class TripDocumentation(Base):
    """
    TripDocumentation model - Legal and travel documentation for a trip
    Generated by AI, stored per trip, one record per trip (unique FK)
    """
    __tablename__ = "trip_documentation"

    id = Column(Integer, primary_key=True, index=True)
    trip_id = Column(
        Integer,
        ForeignKey("trips.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,   # One documentation record per trip
        index=True,
    )

    # Origin country derived from trip.origin (e.g. "India" from "Mumbai")
    origin_country = Column(String, nullable=True)

    # ── 4 core JSON sections ────────────────────────────────────────

    # Document checklist — passport, visa, insurance, photos etc.
    # Structure: [{ destination, visa_type, visa_cost, processing_days,
    #               apply_url, procedure, checklist_items: [{item, required, notes}] }]
    document_checklist = Column(JSON, nullable=True)

    # Entry requirements — health, customs, restricted items, minors
    # Structure: [{ destination, items: [{category, description, details}] }]
    entry_requirements = Column(JSON, nullable=True)

    # Legal advisories — laws, LGBTQ+, drones, photography etc.
    # Structure: [{ destination, advisories: [{severity, category, description}] }]
    legal_advisories = Column(JSON, nullable=True)

    # Emergency contacts — embassy, police, ambulance, hospitals
    # Structure: [{ destination, police, ambulance, embassy_phone,
    #               embassy_address, hospital_recommendations,
    #               travel_advisory_level }]
    emergency_contacts = Column(JSON, nullable=True)

    # Metadata
    generated_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationship back to Trip
    trip = relationship("Trip", back_populates="documentation")

    def __repr__(self):
        return f"<TripDocumentation(id={self.id}, trip_id={self.trip_id})>"
