"""add flights table and trip relationship

Revision ID: 07c06540ff20
Revises: 76e0d7e3e586
Create Date: 2026-01-08 12:39:43.043937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c06540ff20'
down_revision: Union[str, None] = '76e0d7e3e586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('trip_day_id', sa.Integer(), nullable=True),
    sa.Column('flight_number', sa.String(), nullable=True),
    sa.Column('airline', sa.String(), nullable=False),
    sa.Column('airline_code', sa.String(), nullable=True),
    sa.Column('departure_airport', sa.String(), nullable=False),
    sa.Column('arrival_airport', sa.String(), nullable=False),
    sa.Column('departure_city', sa.String(), nullable=True),
    sa.Column('arrival_city', sa.String(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=True),
    sa.Column('layover_airports', sa.JSON(), nullable=True),
    sa.Column('cabin_class', sa.String(), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('price_currency', sa.String(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('booking_url', sa.String(), nullable=True),
    sa.Column('booking_reference', sa.String(), nullable=True),
    sa.Column('aircraft_type', sa.String(), nullable=True),
    sa.Column('baggage_allowance', sa.JSON(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
