"""Add meta_data to disruption_options

Revision ID: 325da9f8db27
Revises: 6871d1e2d547
Create Date: 2026-03-02 19:29:19.737973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325da9f8db27'
down_revision: Union[str, None] = '6871d1e2d547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disruption_options', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disruption_options', 'meta_data')
    # ### end Alembic commands ###
