"""add_trip_collaborators_table

Revision ID: 424c487e3af3
Revises: d5cf59621d9a
Create Date: 2026-03-10 14:48:24.259380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424c487e3af3'
down_revision: Union[str, None] = 'd5cf59621d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('VIEWER', 'EDITOR', name='collaboratorrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='collaboratorstatus'), nullable=False),
    sa.Column('invite_token', sa.String(length=36), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_collaborators_clerk_user_id'), 'trip_collaborators', ['clerk_user_id'], unique=False)
    op.create_index(op.f('ix_trip_collaborators_email'), 'trip_collaborators', ['email'], unique=False)
    op.create_index(op.f('ix_trip_collaborators_id'), 'trip_collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_trip_collaborators_invite_token'), 'trip_collaborators', ['invite_token'], unique=True)
    op.create_index(op.f('ix_trip_collaborators_trip_id'), 'trip_collaborators', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_users_clerk_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_clerk_id'), 'users', ['clerk_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trip_collaborators_trip_id'), table_name='trip_collaborators')
    op.drop_index(op.f('ix_trip_collaborators_invite_token'), table_name='trip_collaborators')
    op.drop_index(op.f('ix_trip_collaborators_id'), table_name='trip_collaborators')
    op.drop_index(op.f('ix_trip_collaborators_email'), table_name='trip_collaborators')
    op.drop_index(op.f('ix_trip_collaborators_clerk_user_id'), table_name='trip_collaborators')
    op.drop_table('trip_collaborators')
    # ### end Alembic commands ###
