"""Add draft_message model

Revision ID: 6871d1e2d547
Revises: f3192f536e12
Create Date: 2026-01-17 18:41:51.650642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6871d1e2d547'
down_revision: Union[str, None] = 'f3192f536e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disruption_case_id', sa.Integer(), nullable=False),
    sa.Column('disruption_option_id', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.Enum('AIRLINE', 'HOTEL', 'INSURANCE', 'OTHER', name='messagerecipienttype'), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('recipient_email', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tone', sa.Enum('FORMAL', 'FIRM', 'FRIENDLY', name='messagetone'), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('attachments_needed', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disruption_case_id'], ['disruption_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disruption_option_id'], ['disruption_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_messages_disruption_case_id'), 'draft_messages', ['disruption_case_id'], unique=False)
    op.create_index(op.f('ix_draft_messages_id'), 'draft_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_messages_id'), table_name='draft_messages')
    op.drop_index(op.f('ix_draft_messages_disruption_case_id'), table_name='draft_messages')
    op.drop_table('draft_messages')
    # ### end Alembic commands ###
