"""Add disruption_chat_messages table

Revision ID: 86ec6e94d4db
Revises: b468e4e09d7e
Create Date: 2026-03-03 17:22:13.176186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ec6e94d4db'
down_revision: Union[str, None] = 'b468e4e09d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruption_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disruption_case_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disruption_case_id'], ['disruption_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruption_chat_messages_disruption_case_id'), 'disruption_chat_messages', ['disruption_case_id'], unique=False)
    op.create_index(op.f('ix_disruption_chat_messages_id'), 'disruption_chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disruption_chat_messages_id'), table_name='disruption_chat_messages')
    op.drop_index(op.f('ix_disruption_chat_messages_disruption_case_id'), table_name='disruption_chat_messages')
    op.drop_table('disruption_chat_messages')
    # ### end Alembic commands ###
