"""add_trip_documentation_table

Revision ID: 9dd307ef780e
Revises: 424c487e3af3
Create Date: 2026-03-15 14:54:22.485466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd307ef780e'
down_revision: Union[str, None] = '424c487e3af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_documentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('origin_country', sa.String(), nullable=True),
    sa.Column('document_checklist', sa.JSON(), nullable=True),
    sa.Column('entry_requirements', sa.JSON(), nullable=True),
    sa.Column('legal_advisories', sa.JSON(), nullable=True),
    sa.Column('emergency_contacts', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_documentation_id'), 'trip_documentation', ['id'], unique=False)
    op.create_index(op.f('ix_trip_documentation_trip_id'), 'trip_documentation', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_documentation_trip_id'), table_name='trip_documentation')
    op.drop_index(op.f('ix_trip_documentation_id'), table_name='trip_documentation')
    op.drop_table('trip_documentation')
    # ### end Alembic commands ###
