"""Add is_favorite column to trips table

Revision ID: b0834f894dc7
Revises: 38ff1d9d3909
Create Date: 2026-01-14 16:03:19.603537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0834f894dc7'
down_revision: Union[str, None] = '38ff1d9d3909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ✅ Add this line: Set default value for existing rows
    op.execute("UPDATE trips SET is_favorite = FALSE WHERE is_favorite IS NULL")
    
    # Now make it non-nullable with default
    op.alter_column('trips', 'is_favorite', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_favorite')
    # ### end Alembic commands ###
