"""Add airlines table

Revision ID: b468e4e09d7e
Revises: 325da9f8db27
Create Date: 2026-03-02 23:24:09.014884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b468e4e09d7e'
down_revision: Union[str, None] = '325da9f8db27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('iata_code', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('customer_service_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airlines_iata_code'), 'airlines', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airlines_id'), 'airlines', ['id'], unique=False)
    op.create_index(op.f('ix_airlines_name'), 'airlines', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airlines_name'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_id'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_iata_code'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
