"""Add disruption models

Revision ID: f3192f536e12
Revises: b0834f894dc7
Create Date: 2026-01-15 20:26:30.082011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3192f536e12'
down_revision: Union[str, None] = 'b0834f894dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruption_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('disruption_date', sa.DateTime(), nullable=False),
    sa.Column('disruption_type', sa.Enum('DELAY', 'CANCELLATION', 'WEATHER', 'STRIKE', 'OTHER', name='disruptiontype'), nullable=False),
    sa.Column('current_status', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='disruptionseverity'), nullable=True),
    sa.Column('pnr', sa.String(length=50), nullable=True),
    sa.Column('booking_reference', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruption_cases_disruption_date'), 'disruption_cases', ['disruption_date'], unique=False)
    op.create_index(op.f('ix_disruption_cases_flight_number'), 'disruption_cases', ['flight_number'], unique=False)
    op.create_index(op.f('ix_disruption_cases_id'), 'disruption_cases', ['id'], unique=False)
    op.create_index(op.f('ix_disruption_cases_user_id'), 'disruption_cases', ['user_id'], unique=False)
    op.create_table('disruption_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disruption_case_id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.Enum('ALTERNATIVE_FLIGHT', 'REFUND', 'HOTEL_VOUCHER', 'COMPENSATION', 'MEAL_VOUCHER', 'REBOOKING', name='optiontype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('booking_url', sa.String(length=500), nullable=True),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disruption_case_id'], ['disruption_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruption_options_id'), 'disruption_options', ['id'], unique=False)
    op.alter_column('trips', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_disruption_options_id'), table_name='disruption_options')
    op.drop_table('disruption_options')
    op.drop_index(op.f('ix_disruption_cases_user_id'), table_name='disruption_cases')
    op.drop_index(op.f('ix_disruption_cases_id'), table_name='disruption_cases')
    op.drop_index(op.f('ix_disruption_cases_flight_number'), table_name='disruption_cases')
    op.drop_index(op.f('ix_disruption_cases_disruption_date'), table_name='disruption_cases')
    op.drop_table('disruption_cases')
    # ### end Alembic commands ###
